'use client';
import { useEffect, useRef } from 'react';
export default function ContactForm(){
 const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{let active=true;let cleanup:undefined|(()=>void);
 const url='/contact-form.js';
 import(/* @vite-ignore */ url).then(({mountContact})=>{if(active && root.current)cleanup=mountContact(root.current,{publicKey:import.meta.env.VITE_EMAILJS_PUBLIC_KEY,serviceId:import.meta.env.VITE_EMAILJS_SERVICE_ID,templateId:import.meta.env.VITE_EMAILJS_TEMPLATE_ID});}).catch(()=>{if(root.current){const status=root.current.querySelector('[role="status"]');if(status)status.textContent='No pudimos cargar el formulario. Recarga la página para intentarlo de nuevo.';}});
 return ()=>{active=false;cleanup?.();};},[]);
 return <div ref={root}><div className="contact-shell"><aside className="contact-intro"><span className="eyebrow">HABLEMOS DE TU IDEA</span><h3>Tu próximo proyecto<br/>empieza aquí.</h3><p>Cuéntame qué necesitas y conversemos sobre tu proyecto.</p><div className="contact-price"><strong>US$100</strong><span>Precio base para una página simple</span></div><p className="contact-small">Consultar no realiza un cobro ni confirma una contratación.</p></aside><div className="contact-form-panel"><form className="contact-form" onSubmit={event => event.preventDefault()}><div className="contact-row"><label>Nombre completo *<input name="user_name" type="text" autoComplete="name" required maxLength={120} placeholder="Tu nombre"/></label><label>Email *<input name="user_email" type="email" autoComplete="email" required maxLength={254} placeholder="tu@correo.com"/></label></div><div className="contact-row"><label>Teléfono *<input name="phone" type="tel" autoComplete="tel" required maxLength={40} placeholder="+56 9 1234 5678"/></label><label>Empresa o proyecto *<input name="company" type="text" autoComplete="organization" required maxLength={160} placeholder="Nombre de tu proyecto"/></label></div><div className="contact-row"><label>Servicio de interés *<select name="services" required><option value="Creación y publicación de página simple">Creación y publicación de página simple</option><option value="Asesoría en inteligencia artificial">Asesoría en inteligencia artificial</option><option value="Automatización de procesos">Automatización de procesos</option><option value="Capacitación o charla">Capacitación o charla</option><option value="Creación de videos para marcas">Creación de videos para marcas</option><option value="Colaboración con marca">Colaboración con marca</option><option value="Otro">Otro</option></select></label><label>Presupuesto *<select name="budget" required><option value="Desde US$100 — página simple">Desde US$100 — página simple</option><option value="Por definir">Por definir</option></select></label></div><label>Cuéntame tu proyecto *<textarea name="message" rows={5} required minLength={50} maxLength={5000} aria-describedby="message-count" placeholder="¿Qué haces, qué quieres mostrar y qué estilo te gustaría para tu página?"></textarea><small id="message-count" data-count="true">0 / 50 caracteres mínimos</small></label><p className="contact-small">Usaremos estos datos para responder tu consulta. El mensaje se procesa a través de EmailJS.</p><button className="hero-button" type="submit" disabled>Enviar mi proyecto ↗</button></form><p className="contact-status" role="status" aria-live="polite"></p></div></div></div>;
}
